### ISSUE TITLE
Compile from source in Debian Jessie 8

### ISSUE THREAD

**Issue by alex-dem** [satoken/ipknot#1]
Hello,

I am trying to compile ipknot from source, but I cannot do it  successfully compile.
I have compiled and installed ViennaRNA 2.19 and I run 
./configure --with-vienna-rna=/home/alexdem/ViennaRNA  --with-glpk
however, when I run make I get multiple errors of this type:

fold.cpp:255:48: error: invalid conversion from ‘char**’ to ‘const char**’ [-fpermissive]
   double min_en = Vienna::alifold(seqs, &res[0]);

Any ideas?

Thank you

**Comment by satoken** [comment]
Hello, 

If you are using ViennaRNA packages built with the default setting, i.e., enabling OpenMP, the option '-fopenmp' for gcc compiler should be needed. Please see: https://github.com/satoken/dafs/issues/1

Best regards,

**Comment by alex-dem** [comment]
Thank you for the prompt reply!
Now it works perfectly.

Best regards,

Alexandros
