### ISSUE TITLE
Failure in the Ipknot compilation

### ISSUE THREAD

**Issue by gurgese** [satoken/ipknot#2]
Dear Dr. Kengo Sato
I got unexpected problems when try to compile Ipknot source code, the logfile is attached.

Can you please suggest me a solution?
Best regards
[Ipknot_error_log.txt](https://github.com/satoken/ipknot/files/106985/Ipknot_error_log.txt)

**Comment by satoken** [comment]
This problem was caused by changing the definition of 'FLT_OR_DBL' at the latest Vienna RNA package 2.2.0. Now, the newest IPknot supports this modification.
Thanks.
