### ISSUE TITLE
Failure in the ipknot execution with alignment input

### ISSUE THREAD

**Issue by joergi-w** [satoken/ipknot#3]
Dear Dr. Kengo Sato,
I get an unexpected error when running ipknot on the attached alignment: [fs10.aln.txt](https://github.com/satoken/ipknot/files/5401969/fs10.aln.txt)

```console
$ ipknot fs10.aln
glp_add_cols: ncs = 0; invalid number of columns
Error detected in file api/prob1.c at line 362
[1]    33727 abort      ipknot fs10.aln
```

It seems to be an invalid call of a glpk function. Can you please suggest me a solution?
Kind regards

**Comment by satoken** [comment]
Thanks for the report.
We will fix this bug in the next update.

Thanks,
