### ISSUE TITLE
Differences between terminal, online activation of ipknot

### ISSUE THREAD

**Issue by Nature091002** [satoken/ipknot#4]
Dear Dr. Kengo Sato,

I tried to test the sample file (drz_Ppac_1_1.fa) online and terminal.

When I set to level 1: 2, level 2: 16 (online)/ -g 2 -g 16 (terminal), these results are different.

Can you give me a suggestion or solution for this?

Kind regards
![Online](https://user-images.githubusercontent.com/83535190/117409771-88a7b680-af4c-11eb-9c31-a4d3f17e9f65.png)
![terminal](https://user-images.githubusercontent.com/83535190/117410075-e76d3000-af4c-11eb-8fa1-957377846f93.png)

**Comment by satoken** [comment]
Thank you for using IPknot.
Is the version of IPknot you are using in the terminal 0.0.5? The web server version is a bit older, so you may get different results than if you use it in the terminal. We will update the web server version of IPknot to the latest version in the near future.

Thanks,

**Comment by Nature091002** [comment]
Thank you for answering.

Have a nice day!
